# Generated by Django 4.2.3 on 2023-07-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_variant_category_delete_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Awaiting Pickup', 'Awaiting Pickup'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
